const urlInput=document.getElementById("url"),goBtn=document.getElementById("go"),refetchBtn=document.getElementById("refetch"),statusEl=document.getElementById("status"),resultsEl=document.getElementById("results"),resumeEl=document.getElementById("resume"),resumeTextEl=document.getElementById("resumeText"),resumeResetBtn=document.getElementById("resumeReset");
let activeShareId=null,renderedResult=null,lastSavedQuestion=0,saveTimer=null;
const GITHUB_URL="https://github.com/Jalalkhan96",POSITION_PREFIX="qm_popup_position_";
function setStatus(msg,isError){statusEl.textContent=msg;statusEl.className=isError?"error":""}
function positionKey(id){return POSITION_PREFIX+id}
async function readPosition(id){if(!id)return null;try{const o=await chrome.storage.local.get(positionKey(id));return o[positionKey(id)]||null}catch{return null}}
async function writePosition(id,data){if(!id)return;try{await chrome.storage.local.set({[positionKey(id)]:data})}catch{} }
function findVisibleQuestionNumber(){const cards=[...resultsEl.querySelectorAll(".q[data-q-number]")];if(!cards.length)return 0;const top=resultsEl.getBoundingClientRect().top;let best=cards[0],dist=Infinity;for(const c of cards){const d=Math.abs(c.getBoundingClientRect().top-top-6);if(d<dist){dist=d;best=c}}return Number(best.dataset.qNumber)||0}
function saveCurrentPositionSoon(){if(!activeShareId)return;clearTimeout(saveTimer);saveTimer=setTimeout(()=>{const q=findVisibleQuestionNumber();lastSavedQuestion=q||lastSavedQuestion;writePosition(activeShareId,{scrollTop:resultsEl.scrollTop,question:lastSavedQuestion,savedAt:Date.now()})},120)}
function updateActiveCard(){const n=findVisibleQuestionNumber();resultsEl.querySelectorAll(".q.active").forEach(e=>e.classList.remove("active"));if(n){const c=resultsEl.querySelector(`.q[data-q-number="${n}"]`);if(c)c.classList.add("active")}}
function showResume(pos,total){if(!pos||!pos.question){resumeEl.classList.remove("show");return}resumeTextEl.textContent=`Resume at Q${pos.question}${total?` of ${total}`:""}`;resumeEl.classList.add("show")}
async function restorePosition(id,total){const pos=await readPosition(id);showResume(pos,total);if(!pos){lastSavedQuestion=0;return}requestAnimationFrame(()=>requestAnimationFrame(()=>{if(typeof pos.scrollTop==="number")resultsEl.scrollTop=Math.max(0,pos.scrollTop);else if(pos.question){const c=resultsEl.querySelector(`.q[data-q-number="${pos.question}"]`);if(c)c.scrollIntoView({block:"start"})}lastSavedQuestion=Number(pos.question)||0;updateActiveCard()}))}
function render(result,fromCache){renderedResult=result;resultsEl.innerHTML="";if(result.randomizeQuestions||result.randomizeOptions){const w=document.createElement("div");w.className="warn";w.textContent="⚠️ This quiz shuffles "+[result.randomizeQuestions?"questions":null,result.randomizeOptions?"options":null].filter(Boolean).join(" and ")+". Match answers by TEXT, not by letter — the letters refer to the original order.";resultsEl.appendChild(w)}const meta=document.createElement("div");meta.className="meta";const age=Math.max(0,Math.round((Date.now()-result.fetchedAt)/1000));const l=document.createElement("span"),r=document.createElement("span");l.textContent=`${result.title} — ${result.questions.length} questions`;r.textContent=fromCache?`cached ${age}s`:"fresh";meta.append(l,r);resultsEl.appendChild(meta);result.questions.forEach(q=>{const div=document.createElement("div");div.className="q";div.dataset.qNumber=String(q.n);const qq=document.createElement("div");qq.className="qq";qq.textContent=`Q${q.n} [${q.type}]: ${q.question}`;const ans=document.createElement("div");ans.className="ans";const b=document.createElement("b");b.textContent=q.correctOption||"?";ans.append(b,document.createTextNode(q.correctText||"answer not found"));div.append(qq,ans);resultsEl.appendChild(div)});restorePosition(activeShareId,result.questions.length)}
async function run(id,force){activeShareId=id;goBtn.disabled=true;refetchBtn.disabled=true;setStatus(force?"Re-fetching answers…":"Fetching answers…");resultsEl.innerHTML="";resumeEl.classList.remove("show");try{const {result,fromCache}=await qmGetAnswers(id,force);setStatus("");render(result,fromCache)}catch(e){setStatus("Error: "+e.message,true)}goBtn.disabled=false;refetchBtn.disabled=false}
function currentId(){return qmExtractShareId(urlInput.value.trim())}
goBtn.addEventListener("click",()=>{const id=currentId();if(!id)return setStatus("Paste a quizmagic.io/session/ link.",true);run(id,false)});
refetchBtn.addEventListener("click",()=>{const id=currentId();if(!id)return setStatus("Paste a quizmagic.io/session/ link.",true);run(id,true)});
resultsEl.addEventListener("scroll",()=>{updateActiveCard();saveCurrentPositionSoon()});
resumeResetBtn.addEventListener("click",async()=>{if(!activeShareId)return;resultsEl.scrollTop=0;lastSavedQuestion=1;await writePosition(activeShareId,{scrollTop:0,question:1,savedAt:Date.now()});updateActiveCard();showResume({question:1},renderedResult?renderedResult.questions.length:0)});
document.getElementById("github").addEventListener("click",e=>{e.preventDefault();chrome.tabs.create({url:GITHUB_URL})});
window.addEventListener("pagehide",saveCurrentPositionSoon);
chrome.tabs.query({active:true,currentWindow:true},tabs=>{const tabUrl=tabs&&tabs[0]?tabs[0].url:"",id=qmExtractShareId(tabUrl);if(id){urlInput.value=tabUrl;run(id,false)}else setStatus("Open a quizmagic.io/session/ link, or paste one above.")});
